//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosovDemoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public int AgentId { get; set; }
        public int ClientId { get; set; }
        public string RealEstateId { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual client client { get; set; }
    }
}
